function cellconnectivity_tags(VERTEX_params,ID_Matrix,group_boundaries,directory,filename)
%cellconnectivity_tags() produces a txt file containing connectivity with 
% neuroml-like tags using ID_Matrix and group_boundaries generated by cellconnectivity.m

if iscell(VERTEX_params)==1
    start=1;
    b=VERTEX_params{1}.numGroups;
    Index_array=cell(b,b); % preallocate index_array for index vectors; row index marks presynaptic population, 
    % whereas column index marks postsynaptic population.
    Group_members=cell(1,b);
    for i=1:b
        
        Index_vector=(VERTEX_params{1}.groupBoundaryIDArr(i)+1):VERTEX_params{1}.groupBoundaryIDArr(i+1);
        Group_members{1,i}=Index_vector;
        if isempty(Index_vector)~=1
            for j=1:b
                
                Index_array{i,j}=find(ID_Matrix(4,start:group_boundaries(Index_vector(end)))==j-1);
                
            end
            start=group_boundaries(Index_vector(end))+1;
        end
        
        
    end

    
end
if isstruct(VERTEX_params)==1
    
    start=1;
    b=VERTEX_params.TissueParams.numGroups;
    Index_array=cell(b,b);
    Group_members=cell(1,b);
    for i=1:b
        
        Index_vector=(VERTEX_params.TissueParams.groupBoundaryIDArr(i)+1):VERTEX_params.TissueParams.groupBoundaryIDArr(i+1);
        Group_members{1,i}=Index_vector;
        if isempty(Index_vector)~=1
            for j=1:b
                
                Index_array{i,j}=find(ID_Matrix(4,start:group_boundaries(Index_vector(end)))==j);
                
                
            end
            start=group_boundaries(Index_vector(end))+1;
        end
        
        
    end
end

projection_counter=0;
t=sprintf('%s%s.txt',directory,filename);
fileID=fopen(t,'w');
for i=1:b
    if isempty(Group_members{1,i})~=1
        for j=1:b
            if isempty(Index_array{i,j})~=1
                projection_tag=sprintf('<projection id="%d" presynapticPopulation="%d" postsynapticPopulation="%d">',projection_counter,i-1,j-1);
                fprintf(fileID,'%s\r\n',projection_tag);
                No_of_connections=length(Index_array{i,j});
                projection_data=ID_Matrix(:,[Index_array{i,j}]);
                for k=1:No_of_connections
                    connection_tag=sprintf('  <connection id="%d" preCellId="%d" postCellId="%d" postSegmentId="%d"/>',k-1,projection_data(1,k),projection_data(3,k),projection_data(5,k));
                    fprintf(fileID,'%s\r\n',connection_tag);
                end
                fprintf(fileID,'%s\r\n\r\n','</projection>');
                projection_counter=projection_counter+1;
            end
        end
    
    end
    
    
end





